config/routes.rb
Quaketracker::Application.routes.draw do
  get 'earthquakes', to: 'quakes#index', as: 'quakes' 
  match 'near_me', to: 'quakes#nearme', as: 'nearme', via: [:get, :post]

  root to: 'quakes#nearme'
end

app/models/quake.rb
class Quake < ActiveRecord::Base
  $keys = [ "src", "eqid", "datetime", "latitude", "longitude", "magnitude", "depth", "nst", "region" ]
  include GeoHelper

  default_scope order("datetime DESC")

  attr_accessible *$keys

  validates :datetime,  :presence => true, :uniqueness => { :scope => [:latitude, :longitude] }
  validates :latitude,  :presence => true
  validates :longitude, :presence => true
  validates :magnitude, :presence => true

  # reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode

  def self.update_from_csv(csv)
    load_from_csv(csv, true)
  end

  def self.get_all_from_csv(csv)
    load_from_csv(csv, false)
  end

  def self.on(unix_time, quakes = self)
    t = Time.at(unix_time)
    where("datetime > ? AND datetime <= ?",
                 t.beginning_of_day, t.end_of_day)
  end

  def self.since(unix_time, quakes = self)
    time = Time.at(unix_time)
    where("datetime >= ?", time)
  end

  def self.over(magnitude, quakes = self)
    where("magnitude >= ?", magnitude)
  end

  # NOTE this an within unfortunately return an array and not an activerelation -
  # this has to be the last query in the string of them
  def self.near5(lat, lon, quakes = self)
    within(lat,lon,5)
  end

  # quakes within n miles of lat,lon
  def self.within(lat, lon, n) # miles
    box = Geocoder::Calculations.bounding_box([lat, lon], n)
    within_box(*box).keep_if do |e|
      e.within?(lat, lon, n)
    end
  end

  def self.within_box(lat1, lon1, lat2, lon2)
    where("latitude >= ? AND longitude >= ? AND latitude <= ? AND longitude <= ?",
          lat1, lon1, lat2, lon2)
  end
  
  def within?(lat, lon, dist)
    GeoHelper.distance(lat, lon, latitude, longitude) <= dist
  end

  def small_json
    to_json(:only => [:datetime, :latitude, :longitude, :magnitude])
  end

  private

  def self.correct_attrs(attrs) # because we import from 2 sources which aren't exactly the same
    attrs['latitude']  = attrs.delete('lat') if(attrs['lat'])
    attrs['longitude'] = attrs.delete('lon') if(attrs['lon'])
    attrs['src'] = attrs.delete('source') if(attrs['source'])

    attrs.each_key do |k|
      attrs.delete k unless $keys.include? k
    end

    attrs
  end
    
  def self.from_csv_line(headers, line)
    attrs = Hash[ headers.zip(line) ]
    self.correct_attrs(attrs)
    return Quake.new(attrs)
  end

  def self.load_from_csv(csv, only_recent)
    time_cutoff = Quake.first.nil? ? Time.at(-9999999999) : Quake.first.datetime
    headers = csv.shift.map(&:downcase)
    added_records = []

    while row = csv.shift do
      q = from_csv_line(headers, row)
      break if (only_recent && q.datetime < time_cutoff)
      if q.save
        p "saved earthquake occuring at #{q.datetime}"
        added_records << q 
      else
        p "skipped earthquake occuring at #{q.datetime}, #{q.latitude}, #{q.longitude}"
      end
    end
    
    added_records
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quakes_controller.rb
class QuakesController < ApplicationController
  # GET /nearme
  # GET /quakes.json
  def nearme
    if params[:address]
      @address = params[:address]
      @latitude, @longitude = Geocoder.coordinates @address
      @update_search = true
    elsif params[:latitude] && params[:longitude]
      @latitude, @longitude = params[:latitude].to_f, params[:longitude].to_f
      @update_search = true unless params[:from_drag]
    else
      @latitude, @longitude = 45.37206, -122.642616
    end

    d = 3
    @quakes = Quake.within_box(@latitude - d, @longitude - 3*d,
                               @latitude + d, @longitude + 3*d).over(1.0)
    respond_to do |format|
      format.js
      format.html
      format.json { render json: @quakes }
    end
  end

  # GET /quakes
  # GET /quakes.json
  def index
    parse_search_params
    @quakes = Quake.all if @quakes == Quake

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quakes }
    end
  end

  # GET /quakes/1
  # GET /quakes/1.json
  def show
    @quake = Quake.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js { render 'move_to' } # index.js.erb
      format.json { render json: @quake }
    end
  end

  private
  
  def parse_search_params
    @quakes ||= Quake
    if params[:over]
      @magnitude = params[:over].to_f
      @quakes = @quakes.over(@magnitude)
    end

    if params[:since]
      @quakes = @quakes.since(params[:since].to_i)
    end

    if params[:on]
      @quakes = @quakes.on(params[:on].to_i)
    end

    if params[:near]
      lat, lon = params[:near].split(",").map(&:to_f)
      @quakes = @quakes.near5(lat, lon, @quakes)
    end

    @quakes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geo_helper.rb
module GeoHelper
  def self.radians(n)
    n * Math::PI / 180
  end

  def self.distance(lat1, lon1, lat2, lon2)
    radius = 6371 # in KM
    dLat = radians (lat2-lat1)
    dLon = radians (lon2-lon1)
    lat1 = radians lat1
    lat2 = radians lat2

    # taken from http://andrew.hedges.name/experiments/haversine/
    # haversine method - already a little inaccurate because it doesn't take into account 
    # the spherical shape of the earth, but also a bit off with the example calculation.
    # It should still be reasonably accurate for our purposes though
    a = Math.sin(dLat/2)**2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon/2)**2 
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
    radius * c
  end
end

app/helpers/google_helper.rb
module GoogleHelper
  def google_api_key
    "YOUR API KEY GOES HERE"
  end
end

app/helpers/quakes_helper.rb
module QuakesHelper
  def latitude
    "#{@latitude}&deg N".html_safe
  end

  def longitude
    "#{@longitude}&deg E".html_safe
  end

  def map_at(lat, lon)
    [ "http://maps.googleapis.com/maps/api/staticmap?",
      "center=#{lat},#{lon}&",
      "markers=color:green%7Clabel:G%7C#{lat},#{lon}&",
      "zoom=5&",
      "size=640x400&",
      "scale=1&",
      "maptype=terrain&",
      "sensor=#{!@from_user.nil?}" ].join("")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quaketracker</title>

  <% if content_for? :head %>
    <%= yield :head %>
  <% end %>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quakes/_form.html.erb
<%= form_for(@quake) do |f| %>
  <% if @quake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quake.errors.count, "error") %> prohibited this quake from being saved:</h2>

      <ul>
      <% @quake.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quakes/_quake_data.html.erb
<div class=hidden id=quakes><%= @quakes.map(&:small_json).join("\n") %></div>

app/views/quakes/_search_bar.html.erb
<div class=search_bar>
  <div class=previous_search>
  Showing earthquakes near 
  <% if @address %> 
    <%= @address %>
  <% else %>
    <%= "#{latitude}, #{longitude}".html_safe %>
  <% end %>
  </div>
  <%= form_tag nearme_path, method: :get, remote: true do %>
    <%= label_tag 'Search' %>
    <%= text_field_tag 'address' %>
  <% end %>
</div>

app/views/quakes/edit.html.erb
<h1>Editing quake</h1>

<%= render 'form' %>

<%= link_to 'Show', @quake %> |
<%= link_to 'Back', quakes_path %>

app/views/quakes/index.html.erb
<h1>Listing quakes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quakes.each do |quake| %>
  <tr>
    <td><%= link_to 'Show', quake %></td>
    <td><%= link_to 'Edit', edit_quake_path(quake) %></td>
    <td><%= link_to 'Destroy', quake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quake', new_quake_path %>

app/views/quakes/nearme.html.erb
<!DOCTYPE html>
<% content_for :head do %>
  <style type="text/css">
    html { height: 100% }
    body { height: 100%; margin: 0; padding: 0 }
    #map-canvas { height: 400px; width:100%; }
  </style>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=<%= google_api_key %>&sensor=false">
  </script>
<% end %>

<%= render 'search_bar' %>

<div id="map-canvas"></div>

<%= render 'quake_data' %>

<script type="text/javascript">
  $(function() { init_map(<%=@latitude%>, <%=@longitude%>) })
  //$(function() { initialize() })
</script>

app/views/quakes/nearme.js.erb
<% if @update_search %>
  $('.search_bar').replaceWith('<%= j render(:partial => 'search_bar') %>');
<% end %>

//alert('replacing quakes');
$('#quakes').replaceWith('<%= j render('quake_data') %>');
// alert('initalizing map');
init_map(<%= @latitude %>, <%= @longitude %>, true)

app/views/quakes/new.html.erb
<h1>New quake</h1>

<%= render 'form' %>

<%= link_to 'Back', quakes_path %>

app/views/quakes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_quake_path(@quake) %> |
<%= link_to 'Back', quakes_path %>